"""Intelligence layer (Phase 3) — pure Python, bilingual (Arabic + English).

No ML deps, no API keys: runs fully offline on the Saudi node. Produces
language, summary, keywords, entities, topic/category, sentiment, and an
importance score for each article.

LLM upgrade path: set an `llm_summarizer` callable via set_llm_summarizer()
and summaries will be generated by it instead of the extractive fallback —
nothing else in the pipeline changes.
"""
from __future__ import annotations

import re
from collections import Counter

# ----------------------------------------------------------------- language ---
_ARABIC_RE = re.compile(r"[؀-ۿ]")


def detect_language(text: str) -> str:
    if not text:
        return "unknown"
    arabic = len(_ARABIC_RE.findall(text))
    letters = len(re.findall(r"[^\W\d_]", text, flags=re.UNICODE)) or 1
    return "ar" if arabic / letters > 0.3 else "en"


# ------------------------------------------------------------------ stopwords ---
_EN_STOP = set(
    "the a an and or but of to in on for with at by from as is are was were be been "
    "this that these those it its has have had will would can could should may might "
    "said says new news report reports year years today after before over under more "
    "most some any all not no into out up down about than then so such we you they he "
    "she his her their our your i me my".split()
)
_AR_STOP = set(
    "في من على إلى عن أن إن أو و ثم قد كان كانت يكون التي الذي الذين هذا هذه ذلك تلك "
    "ما لا لم لن هو هي هم نحن أنت كل بعض غير بين خلال بعد قبل عند منذ حتى مع كما حيث "
    "اليوم أمس قال قالت وقال أكد أوضح أعلن الى انه وانه يوم العام السعودية المملكة".split()
)
_STOP = _EN_STOP | _AR_STOP

_TOKEN_RE = re.compile(r"[؀-ۿA-Za-z][؀-ۿA-Za-z\-']{2,}")


def _tokens(text: str) -> list[str]:
    return [t for t in _TOKEN_RE.findall(text or "")]


def extract_keywords(text: str, limit: int = 10) -> list[str]:
    counts = Counter(
        t.lower() for t in _tokens(text) if t.lower() not in _STOP and len(t) > 2
    )
    return [w for w, _ in counts.most_common(limit)]


# ------------------------------------------------------------------- summary ---
_SENT_SPLIT = re.compile(r"(?<=[\.\!\?؟۔])\s+|\n+")
_llm_summarizer = None  # optional callable(text, title) -> str


def set_llm_summarizer(fn) -> None:
    global _llm_summarizer
    _llm_summarizer = fn


def summarize(text: str, title: str = "", max_sentences: int = 4) -> str:
    if _llm_summarizer is not None:
        try:
            out = _llm_summarizer(text, title)
            if out:
                return out.strip()
        except Exception:
            pass  # fall through to extractive
    text = (text or "").strip()
    if not text:
        return ""
    sentences = [s.strip() for s in _SENT_SPLIT.split(text) if len(s.strip()) > 20]
    if not sentences:
        return text[:300]
    # Extractive: rank sentences by keyword overlap, keep original order.
    kw = set(extract_keywords(text, 15))
    scored = []
    for idx, sent in enumerate(sentences[:40]):
        score = sum(1 for t in _tokens(sent) if t.lower() in kw)
        score += 1.5 if idx == 0 else 0  # lead bias
        scored.append((score, idx, sent))
    top = sorted(scored, key=lambda x: -x[0])[:max_sentences]
    return " ".join(s for _, _, s in sorted(top, key=lambda x: x[1]))


# ------------------------------------------------------------------- topics ---
# Bilingual keyword gazetteer. First topic with the highest hit-count wins.
TOPIC_GAZETTEER = {
    "Economy": ["economy", "gdp", "inflation", "budget", "trade", "اقتصاد", "ميزانية", "تضخم", "تجارة", "ناتج"],
    "Finance": ["bank", "stock", "tadawul", "shares", "investment", "fund", "بنك", "أسهم", "تداول", "استثمار", "صندوق", "مصرف"],
    "Energy": ["oil", "gas", "aramco", "energy", "barrel", "opec", "نفط", "غاز", "أرامكو", "طاقة", "برميل", "أوبك", "كهرباء"],
    "Technology": ["technology", "digital", "software", "internet", "cyber", "تقنية", "رقمي", "برمجيات", "إنترنت", "سيبراني"],
    "AI": ["artificial intelligence", "machine learning", "sdaia", "ذكاء اصطناعي", "سدايا", "تعلم الآلة", "نموذج لغوي"],
    "Startups": ["startup", "venture", "founder", "funding round", "شركة ناشئة", "ريادة", "تمويل", "مؤسس"],
    "Government": ["ministry", "minister", "government", "royal", "decree", "authority", "وزارة", "وزير", "حكومة", "ملكي", "مرسوم", "هيئة", "أمر"],
    "Politics": ["political", "diplomatic", "summit", "foreign", "relations", "سياسي", "دبلوماسي", "قمة", "خارجية", "علاقات"],
    "Defense": ["military", "defense", "army", "security forces", "missile", "عسكري", "دفاع", "جيش", "قوات", "صاروخ", "أمن"],
    "Energy_Vision": ["neom", "vision 2030", "qiddiya", "roshn", "red sea", "diriyah", "نيوم", "رؤية 2030", "القدية", "روشن", "البحر الأحمر", "الدرعية"],
    "Sports": ["football", "match", "league", "club", "tournament", "كرة", "مباراة", "دوري", "نادي", "بطولة"],
    "Tourism": ["tourism", "tourist", "heritage", "hotel", "travel", "سياحة", "سياح", "تراث", "فندق", "سفر"],
    "Media": ["media", "press", "journalist", "broadcast", "إعلام", "صحافة", "صحفي", "بث"],
    "Health": ["health", "hospital", "medical", "patients", "صحة", "مستشفى", "طبي", "مرضى"],
}


def classify_topic(text: str, title: str = "") -> str:
    blob = f"{title} {title} {text}".lower()  # title weighted x2
    best, best_score = "General", 0
    for topic, terms in TOPIC_GAZETTEER.items():
        score = sum(blob.count(t) for t in terms)
        if score > best_score:
            best, best_score = topic, score
    return "Vision 2030" if best == "Energy_Vision" else best


# ------------------------------------------------------------------ entities ---
# Compact gazetteers for high-precision Saudi entities + generic patterns.
ORG_GAZETTEER = [
    "Aramco", "SABIC", "PIF", "Public Investment Fund", "SAMA", "Tadawul", "CMA",
    "STC", "NEOM", "ROSHN", "Qiddiya", "SDAIA", "GASTAT", "ZATCA", "MISA",
    "أرامكو", "سابك", "صندوق الاستثمارات العامة", "ساما", "تداول", "هيئة السوق المالية",
    "نيوم", "روشن", "القدية", "سدايا", "زاتكا", "وزارة الاستثمار", "البنك المركزي",
]
LOC_GAZETTEER = [
    "Saudi Arabia", "Riyadh", "Jeddah", "Makkah", "Mecca", "Medina", "Dammam",
    "Eastern Province", "Gulf", "GCC", "Red Sea",
    "السعودية", "الرياض", "جدة", "مكة", "المدينة", "الدمام", "الخليج", "البحر الأحمر",
    "المنطقة الشرقية",
]
# Capitalized multi-word sequences = candidate proper nouns (English text).
_PROPER_RE = re.compile(r"\b([A-Z][a-z]+(?:\s+[A-Z][a-z]+){1,3})\b")
_TITLE_HINT = ("Prince", "King", "Minister", "Dr.", "Sheikh", "الأمير", "الملك", "الوزير", "الدكتور", "الشيخ")


def extract_entities(text: str, title: str = "") -> dict:
    blob = f"{title}. {text}"
    orgs = sorted({g for g in ORG_GAZETTEER if g in blob})
    locs = sorted({g for g in LOC_GAZETTEER if g in blob})
    people = []
    for cand in _PROPER_RE.findall(blob):
        if cand in orgs or cand in locs:
            continue
        # Treat as person if preceded by a title hint anywhere nearby.
        if any(h in blob[max(0, blob.find(cand) - 20): blob.find(cand)] for h in _TITLE_HINT):
            people.append(cand)
    people = sorted(set(people))[:10]
    return {"organizations": orgs[:10], "people": people, "locations": locs[:10]}


# ----------------------------------------------------------------- sentiment ---
_POS = set("growth gain rise boost success record launch agreement win award approve expand profit surge improve منتدى نجاح إطلاق نمو ارتفاع اتفاق فوز جائزة موافقة توسع أرباح تحسن إنجاز".split())
_NEG = set("loss decline fall crisis attack war death cut deficit risk warning ban fraud delay drop خسارة تراجع أزمة هجوم حرب وفاة عجز خطر تحذير حظر احتيال تأخير انخفاض".split())


def analyze_sentiment(text: str) -> str:
    toks = [t.lower() for t in _tokens(text)]
    pos = sum(1 for t in toks if t in _POS)
    neg = sum(1 for t in toks if t in _NEG)
    if pos > neg and pos > 0:
        return "positive"
    if neg > pos and neg > 0:
        return "negative"
    return "neutral"


# ---------------------------------------------------------------- importance ---
def importance(item: dict, source_priority: int = 3) -> float:
    """0-100 heuristic: source priority + content depth + entity richness."""
    score = (6 - max(1, min(source_priority, 5))) * 10  # p1 -> 50, p5 -> 10
    content_len = len((item.get("content") or ""))
    score += min(content_len / 100, 30)  # up to +30 for substance
    ent = item.get("entities") or {}
    score += min(sum(len(v) for v in ent.values()) * 2, 20)  # up to +20
    return round(min(score, 100), 1)


# -------------------------------------------------------------------- enrich ---
def enrich(item: dict, source: dict | None = None) -> dict:
    """Add intelligence fields to a normalized article dict (in place)."""
    source = source or {}
    text = item.get("content") or item.get("summary") or ""
    title = item.get("title") or ""

    item["language"] = detect_language(f"{title} {text}")
    item["keywords"] = extract_keywords(f"{title} {text}", 10)
    item["entities"] = extract_entities(text, title)
    item["sentiment"] = analyze_sentiment(f"{title} {text}")
    # Only override category with the classifier when the source didn't pin one
    # to a meaningful topic (sources.json category is a coarse bucket).
    item["category"] = classify_topic(text, title) or item.get("category") or "General"
    if not item.get("summary"):
        item["summary"] = summarize(text, title)
    item["importance_score"] = importance(item, source.get("priority", 3))
    return item
